name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
#  sdk: ">=2.1.0<3.0.0"
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^1.0.8
  shared_preferences: ^0.5.4+5
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.4.1
  provider: ^4.0.1
  firebase_storage: ^5.1.0
  image_picker: ^0.6.7+14
  image_cropper: ^1.3.1
  flutter_launcher_icons: ^0.8.1
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.2.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  modal_progress_hud: ^0.1.3
  string_validator: ^0.1.4
  flutter_spinkit: ^4.1.2

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: "images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/
